# Generated by Django 3.0.6 on 2020-05-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='action',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_joining',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
