# Generated by Django 3.0.6 on 2020-05-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20200526_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(default=100, unique=True),
        ),
    ]
