# Generated by Django 3.0.6 on 2020-05-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=' ', max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=20)),
            ],
        ),
    ]
